batch_size: 32
conc_cols_prefix: CT_CON
dose_col: CT_Dose
eps: 1.0e-06
k: 5
learning_rate: 0.0001
loss_alpha: 24
loss_fn: log_mae_time_exp_decay
method: NeuralODE
node_mid_dim: 128
num_cmpts: 3
num_epochs: 100
output_dim: 7
pretrain: mol_pre_all_h_220816.pt
return_rep: true
route: p.o.
route_col: DoseRoute
save_path: examples/weights/po_model
smiles_col: SMILES
test_filepath: CT1127_clean_iv_test.csv
time_cols_prefix: CT_TIME
train_filepath: ./example/data/CT1127_clean_ivpo_train_val_cmax.csv
vd_mid_dim: 128
warmup_ratio: 0.03
